name: acnh_helper
description: "Animal Crossing: New Horizons helper/tracker."
author: "David Mougey <imapiekindaguy@gmail.com>"
version: 0.8.1
homepage: "https://github.com/ddmgy/acnh_helper"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0
  path: ^1.7.0
  sqflite: ^1.3.0
  provider: ^4.3.0
  search_page: ^1.3.0
  cached_network_image: ^2.3.0
  auto_size_text: ^2.1.0
  flutter_markdown: ^0.5.0
  url_launcher: ^5.7.0
  flutter_colorpicker: ^0.3.0
  shared_preferences: ">=0.5.0 <2.0.0"
  preferences_ui:
    git:
      url: "git://github.com/ddmgy/preferences_ui.git"
      ref: "v0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
  fonts:
    - family: Arial
      fonts:
        - asset: assets/font/Arial-Rounded.ttf
    - family: Fink
      fonts:
        - asset: assets/font/Fink-Heavy.ttf